//apply plugin: 'com.github.hauner.jarTest'
apply plugin: 'idea'

apply from: '../project/assemble.gradle'
apply from: '../project/logging.gradle'

defaultTasks 'clean'

dependencies {
    annotationProcessor(variantOf(libs.querydsl.apt) { classifier('jpa') })
    annotationProcessor libs.javax.annotation.api
    annotationProcessor libs.hibernate.jpa.api

    // The `javax.annotation-api` dependency is (re)declared here as `compileOnly`
    // to allow for annotations that are used in the code generated by QueryDSL.
    compileOnly libs.javax.annotation.api

    api libs.querydsl.jpa
    implementation libs.hibernate.jpa.api
    implementation libs.bundles.jpa.hibernate
}


